packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
<<<<<<< HEAD
  '@platforma-sdk/model': ^1.22.59
  '@platforma-sdk/ui-vue': ^1.22.82
  '@platforma-sdk/workflow-tengo': ^2.15.9
  '@platforma-sdk/block-tools': ^2.5.18
  '@platforma-sdk/test': ^1.22.89
  '@platforma-sdk/tengo-builder': ^1.19.2
  '@milaboratories/graph-maker': ^1.1.54
=======
  '@platforma-sdk/model': ^1.21.20
  '@platforma-sdk/ui-vue': ^1.22.23
  '@platforma-sdk/workflow-tengo': ^2.9.9
  '@platforma-sdk/block-tools': ^2.5.5
  '@platforma-sdk/test': ^1.21.34
  '@platforma-sdk/tengo-builder': ^1.17.5
  '@milaboratories/graph-maker': ^1.1.37
>>>>>>> origin/main
  '@milaboratories/software-pframes-conv': ^2.1.16

  '@platforma-open/milaboratories.software-small-binaries': ^1.15.15
  '@platforma-open/milaboratories.runenv-r-functional-analysis': ^1.0.6
  '@platforma-sdk/package-builder': ^2.15.2
  '@platforma-sdk/eslint-config': ^1.0.1

  'vue': ^3.5.13
  'vue-tsc': ^2.2.8

  'typescript': ^5.6.3
<<<<<<< HEAD
  'tsup': ~8.4.0
=======
  'tsup': ~8.3.5
>>>>>>> origin/main
  'turbo': ^2.4.4

  'vite': ^6.0.11
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  '@changesets/cli': ^2.28.1
