packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/model': ^1.45.30
  '@platforma-sdk/ui-vue': ^1.45.30
  '@platforma-sdk/workflow-tengo': ^5.6.1
  '@platforma-sdk/block-tools': ^2.6.30
  '@platforma-sdk/test': ^1.45.30
  '@platforma-sdk/tengo-builder': ^2.3.9
  '@milaboratories/graph-maker': ^1.1.179
  '@milaboratories/software-pframes-conv': ^2.2.9

  '@platforma-open/milaboratories.runenv-r-functional-analysis': ^1.0.6
  '@platforma-sdk/package-builder': ^3.10.7
  '@platforma-sdk/eslint-config': ^1.1.0
  '@platforma-sdk/blocks-deps-updater': ^2.0.0

  'vue': ^3.5.13
  'vue-tsc': ^2.2.10

  'typescript': ~5.6.3
  'tsup': ~8.4.0
  'turbo': ^2.4.4

  'vite': ^6.0.11
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1
  'shx': ^0.4.0

  '@changesets/cli': ^2.28.1
