packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/model': ^1.39.8
  '@platforma-sdk/ui-vue': ^1.39.10
  '@platforma-sdk/workflow-tengo': ^4.9.3
  '@platforma-sdk/block-tools': ^2.5.67
  '@platforma-sdk/test': ^1.39.11
  '@platforma-sdk/tengo-builder': ^2.1.12
  '@milaboratories/graph-maker': ^1.1.131
  '@milaboratories/software-pframes-conv': ^2.2.2

  '@platforma-open/milaboratories.runenv-r-functional-analysis': ^1.0.6
  '@platforma-sdk/package-builder': ^2.16.2
  '@platforma-sdk/eslint-config': ^1.0.3

  'vue': ^3.5.13
  'vue-tsc': ^2.2.8

  'typescript': ~5.5.4
  'tsup': ~8.4.0
  'turbo': ^2.4.4

  'vite': ^6.0.11
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  "js-yaml": ^4.1.0

  '@changesets/cli': ^2.28.1
