packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/model': ^1.43.2
  '@platforma-sdk/ui-vue': ^1.43.2
  '@platforma-sdk/workflow-tengo': ^5.2.1
  '@platforma-sdk/block-tools': ^2.6.6
  '@platforma-sdk/test': ^1.43.7
  '@platforma-sdk/tengo-builder': ^2.1.21
  '@milaboratories/graph-maker': ^1.1.157
  '@milaboratories/software-pframes-conv': ^2.2.7

  '@platforma-open/milaboratories.runenv-r-functional-analysis': ^1.0.6
  '@platforma-sdk/package-builder': ^3.5.2
  '@platforma-sdk/eslint-config': ^1.1.0
  '@platforma-sdk/blocks-deps-updater': ^2.0.0

  'vue': ^3.5.13
  'vue-tsc': ^2.2.10

  'typescript': ~5.6.3
  'tsup': ~8.4.0
  'turbo': ^2.4.4

  'vite': ^6.0.11
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  '@changesets/cli': ^2.28.1
