packages:
  - software
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.14.1
  "@platforma-sdk/ui-vue": ^1.14.11
  "@platforma-sdk/workflow-tengo": ^2.9.5
  "@platforma-sdk/block-tools": ^2.5.0
  "@platforma-sdk/test": ^1.10.4
  "@platforma-sdk/tengo-builder": ^1.17.4
  "@platforma-sdk/package-builder": ^2.14.2
  "@milaboratories/graph-maker": ^1.1.5

  "@platforma-open/milaboratories.software-small-binaries": ^1.15.6
  "@platforma-open/milaboratories.software-small-binaries.mnz-client": ^1.4.0
  "@platforma-open/milaboratories.runenv-r": ^1.2.11
  
  "vue": ^3.5.13
  "vue-tsc": ^2.1.10
  
  "typescript": ^5.6.3
  "tsup": ~8.3.5
  "turbo": ^2.3.3

  "vite": ^5.4.11
  "vitest": ^2.1.6
  "@vitejs/plugin-vue": ^5.2.1

  "@changesets/cli": ^2.27.10
