packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/model': ^1.42.4
  '@platforma-sdk/ui-vue': ^1.42.4
  '@platforma-sdk/workflow-tengo': ^4.14.1
  '@platforma-sdk/block-tools': ^2.5.77
  '@platforma-sdk/test': ^1.42.4
  '@platforma-sdk/tengo-builder': ^2.1.13
  '@milaboratories/graph-maker': ^1.1.138
  '@milaboratories/software-pframes-conv': ^2.2.2

  '@platforma-open/milaboratories.runenv-r-functional-analysis': ^1.0.6
  '@platforma-sdk/package-builder': ^2.16.2
  '@platforma-sdk/eslint-config': ^1.0.3

  'vue': ^3.5.13
  'vue-tsc': ^2.2.10

  'typescript': ~5.6.3
  'tsup': ~8.4.0
  'turbo': ^2.4.4

  'vite': ^6.0.11
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  "js-yaml": ^4.1.0

  '@changesets/cli': ^2.28.1
