packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/model': ^1.22.59
  '@platforma-sdk/ui-vue': ^1.22.59
  '@platforma-sdk/workflow-tengo': ^2.13.1
  '@platforma-sdk/block-tools': ^2.5.14
  '@platforma-sdk/test': ^1.21.60
  '@platforma-sdk/tengo-builder': ^1.17.7
  '@milaboratories/graph-maker': ^1.1.48
  '@milaboratories/software-pframes-conv': ^2.1.2

  '@platforma-open/milaboratories.software-small-binaries': ^1.15.6
  '@platforma-open/milaboratories.runenv-r': ^1.2.18
  '@platforma-sdk/package-builder': ^2.15.0
  '@platforma-sdk/eslint-config': ^1.0.1

  'vue': ^3.5.13
  'vue-tsc': ^2.2.0

  'typescript': ^5.6.3
  'tsup': ~8.3.5
  'turbo': ^2.3.3

  'vite': ^6.0.11
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  '@changesets/cli': ^2.27.11
